# Generated by Django 2.0.5 on 2018-07-31 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('rateID', models.IntegerField(primary_key=True, serialize=False)),
                ('currencyCode', models.CharField(max_length=3)),
                ('sellPrice', models.DecimalField(decimal_places=6, max_digits=15)),
                ('buyPrice', models.DecimalField(decimal_places=6, max_digits=15)),
                ('date', models.DateTimeField()),
                ('createTime', models.DateTimeField()),
            ],
        ),
    ]
