# Generated by Django 2.0.5 on 2018-07-31 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getrate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyrate',
            name='createTime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='currencyrate',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
